# Generated by Django 2.0.5 on 2018-05-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GobbleGum',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RandomFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='perks',
            field=models.ManyToManyField(blank=True, to='zombies.Perk'),
        ),
        migrations.AddField(
            model_name='location',
            name='map',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zombies.Map'),
        ),
        migrations.AddField(
            model_name='location',
            name='perk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zombies.Perk'),
        ),
        migrations.AddField(
            model_name='fact',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zombies.Map'),
        ),
    ]
