# Generated by Django 2.0.5 on 2018-06-04 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GobbleGum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gobblegum_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('mega_common', 'Mega Common'), ('whimsical', 'Whimsical'), ('classic', 'Classic'), ('mega_rare', 'Mega Rare'), ('mega_ultra_rare', 'Mega Ultra-Rare')], max_length=100)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(default=datetime.datetime(2018, 6, 4, 13, 56, 54, 196515, tzinfo=utc))),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
        migrations.CreateModel(
            name='MapFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zombies.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perk_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zombies.Map')),
            ],
            options={
                'ordering': ('map', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RandomFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='perk',
            unique_together={('map', 'perk_id')},
        ),
    ]
