# Generated by Django 2.0.5 on 2018-06-04 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zombies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 4, 10, 55, 43, 759020, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
