# Generated by Django 2.0.5 on 2018-06-01 17:57
from django.contrib.auth.models import User
from django.db import migrations

from zombies.models import RandomFact, MapFact, Map, Perk, GobbleGum

from voice_zombies2.facts import random_facts, map_facts, map_perk_locations, gobblegum_data



def create_data(apps, schema_editor):
    try:
        User.objects.get(username='test')
    except User.DoesNotExist:
        User.objects.create_superuser('test', 'test@test.com', 'test')

    for fact in random_facts:
        RandomFact.objects.get_or_create(description=fact)

    for map_name, map_fact in map_facts.items():
        map, _ = Map.objects.get_or_create(code=map_name, name=map_name.replace('_', ' ').capitalize())
        MapFact.objects.get_or_create(map=map, description=map_fact)

    for map_name, info in map_perk_locations.items():
        map, _ = Map.objects.get_or_create(code=map_name, name=map_name.replace('_', ' ').capitalize())
        for perk_name, description in info.items():
            Perk.objects.get_or_create(
                map=map, code=perk_name, location=description, name=perk_name.replace('_', ' ').capitalize()
            )

    for gobblegum_name, info in gobblegum_data.items():
        gum, _ = GobbleGum.objects.get_or_create(code=gobblegum_name)
        gum.description = info['description']
        gum.type =info['type']
        gum.name = gobblegum_name.replace('_', ' ').capitalize()
        gum.save()



class Migration(migrations.Migration):


    dependencies = [
        ('zombies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data, reverse_code=migrations.RunPython.noop),
    ]
